#!/usr/bin/env python3
"""Vendor operating-system end-of-life data.

`ism-1501` ("Operating systems that are no longer supported by vendors are
replaced"), `ism-1704` and `ism-1905` all need to know when support ended. That
answer is a date, and dates are exactly the sort of thing a compliance tool must
not guess.

Source: https://endoflife.date (MIT, community-maintained).

An important caveat is carried through to the check's confidence rather than
buried here: **endoflife.date is community-maintained, not vendor-authoritative**.
For a compliance assertion the vendor's own lifecycle page is the authority. So:

  * the check that consumes this reports `proxy` confidence, never `direct`;
  * every record carries its source, so a deployment can override entries with
    vendor-confirmed dates and have that visible in the evidence;
  * data is vendored and checksummed, so an assessment is reproducible and runs
    air-gapped.

Run with --verify to check vendored files against the manifest, offline.
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.parse
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

from ism_release import sha256_file

ROOT = Path(__file__).resolve().parent.parent
EOL_DIR = ROOT / "data" / "eol"
API = "https://endoflife.date/api"
TIMEOUT = 45

#: endoflife.date product slugs we consume. Keep this list to things the
#: repository actually has collectors for -- vendoring data nothing reads is
#: just weight.
#:
#: Slugs are not guessable and were confirmed against the API index: the
#: obvious `microsoft-office`, `google-chrome` and `adobe-flash-player` all
#: 404. What exists is `office`, `chrome`, `firefox`, `libreoffice`,
#: `oracle-jdk`.
PRODUCTS = (
    # Operating systems -- ism-1501, ism-1905.
    "rhel",
    "ubuntu",
    "windows",
    "windows-server",
    "rocky-linux",
    "debian",
    # Applications -- ism-1704.
    "office",
    "chrome",
    "firefox",
    "libreoffice",
    "oracle-jdk",
)

#: Application families ism-1704 names that endoflife.date does NOT carry,
#: confirmed by searching its 477-product index: Microsoft Edge, PDF
#: applications, email clients, security products and browser extensions.
#:
#: This is recorded rather than quietly omitted, because the difference between
#: "checked and supported" and "not checked at all" is the whole point. The
#: ism-1704 evaluator reports these families as uncovered and caps its
#: confidence accordingly.
UNCOVERED_FAMILIES = (
    "Microsoft Edge",
    "PDF applications",
    "email clients",
    "security products",
    "web browser extensions",
)


def fetch(url: str) -> bytes:
    if urllib.parse.urlparse(url).scheme != "https":
        raise ValueError(f"refusing non-HTTPS URL: {url!r}")
    request = urllib.request.Request(  # noqa: S310  (scheme asserted https above)
        url, headers={"User-Agent": "oscal-aap-ansible-playbooks"}
    )
    with urllib.request.urlopen(request, timeout=TIMEOUT) as response:  # noqa: S310
        return response.read()


def download() -> dict:
    EOL_DIR.mkdir(parents=True, exist_ok=True)
    files: dict = {}
    for product in PRODUCTS:
        payload = fetch(f"{API}/{product}.json")
        path = EOL_DIR / f"{product}.json"
        # Normalised with sorted keys so a refresh produces a reviewable diff
        # rather than a reordering. Unlike the ISM catalog this is not
        # redistributed-verbatim material, so reformatting is safe here.
        data = json.loads(payload)
        path.write_text(json.dumps(data, indent=2, sort_keys=True) + "\n", encoding="utf-8")
        files[path.name] = {"sha256": sha256_file(path), "cycles": len(data)}
        print(f"  {product:<16} {len(data):>3} cycles")

    manifest = {
        "_comment": (
            "Generated by tools/fetch_eol_data.py. Do not edit by hand. "
            "endoflife.date is COMMUNITY-MAINTAINED, not vendor-authoritative: "
            "checks consuming this report `proxy` confidence, and a deployment "
            "may override entries with vendor-confirmed dates."
        ),
        "source": "https://endoflife.date",
        "licence": "MIT",
        "copyright": "endoflife.date contributors",
        "authoritative": False,
        "files": dict(sorted(files.items())),
    }
    (EOL_DIR / "MANIFEST.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    return manifest


def verify() -> int:
    manifest_path = EOL_DIR / "MANIFEST.json"
    if not manifest_path.exists():
        print(f"{manifest_path} missing - run `make fetch`", file=sys.stderr)
        return 1
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    problems = []
    for name, meta in manifest["files"].items():
        path = EOL_DIR / name
        if not path.exists():
            problems.append(f"{name}: missing")
        elif sha256_file(path) != meta["sha256"]:
            problems.append(f"{name}: SHA-256 mismatch")
    if problems:
        print("EOL DATA VERIFICATION FAILED:", file=sys.stderr)
        for problem in problems:
            print(f"  {problem}", file=sys.stderr)
        return 1
    print(f"verified {len(manifest['files'])} EOL data files in {EOL_DIR.relative_to(ROOT)}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify", action="store_true", help="check vendored files, offline")
    args = parser.parse_args()
    if args.verify:
        return verify()
    print("Vendoring end-of-life data from endoflife.date")
    download()
    print("\nDone. Re-run with --verify to confirm integrity.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
